import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home({data}) {

  const [searchValue, setSearchValue] = useState('')

  //setDataFood(data.foods)

  const elements = data.foods.map((food =>{
    return(
    <div className={styles.card} key={food.fdcId}>
      <h2 > Description: {food.description}</h2>
      <span > Ingredients: {food.ingredients}</span>
    </div>)

  }))


  return (
    <div className={styles.container}>
      <Head>
        <title>Your Next Food Searcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 >
          Welcome to Food Searcher 
        </h1>
        


        <div className={styles.grid} >
        <section className={styles.section}>
            <input                        
            placeholder='Search posts'
            type='text'
            onKeyUp={(event) =>{ setSearchValue(event.currentTarget.value) }}
          />
           <Link href={`/?term=`+searchValue } as={`/?term=`+searchValue }>
                <a>Search</a>
              </Link>
        </section>
         {elements} 
        </div>


        
        
      </main>

      <footer className={styles.footer}>        
      </footer>
    </div>
  )
}

export async function getServerSideProps({query}){

  const searchTerm = query.term

  const res = await fetch(`https://api.nal.usda.gov/fdc/v1/foods/search?query=${searchTerm}&api_key=${process.env.API_KEY}`)

  const data = await res.json()

  return{
    props:{ data: data}
  }
}